name: Build and Release PowerBI Visual

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build PowerBI visual
        run: npm run build

      - name: Get version from pbiviz.json
        id: get_version
        run: |
          VERSION=$(node -p "require('./pbiviz.json').visual.version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if release exists
        id: check_release
        run: |
          if gh release view "v${{ steps.get_version.outputs.version }}" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Rename output file
        if: steps.check_release.outputs.exists == 'false'
        run: |
          cd dist
          for f in *.pbiviz; do
            version=$(echo $f | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+')
            mv "$f" "NHMzhPbiViewer_v${version}.pbiviz"
          done

      - name: Create Release
        if: steps.check_release.outputs.exists == 'false'
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/NHMzhPbiViewer_v*.pbiviz
          draft: false
          prerelease: false
          generate_release_notes: true
          tag_name: v${{ steps.get_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
